config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  
  devise_for :users, :controllers => { registrations: 'registrations'}
  devise_scope :user do
    get '/sign_up' => 'registrations#new'
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end


  resources :charities do
    member do
      post 'vote'
    end
  end

  resources :subscriptions, only: [:new, :create, :destroy]


end

app/models/charity.rb
class Charity < ActiveRecord::Base

  has_many :votes, as: :voteable

  validates_presence_of :name, :description, :mission_statement, :url

  def total_votes
    self.votes.where(vote: true).size
  end

  def self.winner_of_the_month
    charities = Charity.all
    charity_votes = {}

    charities.each do |c|
      charity_votes[c.name] = c.votes.size
    end

    winner = charity_votes.max_by{ |k,v| v}
    return winner
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :vote
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user_id, scope: [:voteable_type]
 

  def self.reset_charity_votes
    Vote.where(voteable_type: "Charity").delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin?
    if current_user.admin != true
      redirect_to charities_path
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create

    customer = Stripe::Customer.create(
      :source => params[:stripeToken],
      :plan => "gold",
      :email => "#{current_user.email}"
    )

    update_customer_id_and_subscription_id(customer)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
  
  def destroy
    customer = Stripe::Customer.retrieve(current_user.customer_id)
    customer.subscriptions.retrieve(current_user.subscription_id).delete(:at_period_end => true)
  end

private
  def update_customer_id_and_subscription_id(customer)
    stripe_customer_params = JSON.parse(customer.to_s)

    current_user.update_attribute(:customer_id, stripe_customer_params["id"])
    current_user.update_attribute(:subscription_id, stripe_customer_params["subscriptions"]["data"][0]["id"])
    current_user.save
  end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin?, except: [:index, :show, :vote]
  before_action :set_charity, only: [:show, :edit, :update, :destroy, :vote]

  def index
    @charities = Charity.all
  end

  def show
  end

  def new
    @charity = Charity.new
  end

  def create
    @charity = Charity.new(charity_params)

    if @charity.save
      flash[:notice] = "Charity successfully created!"
      redirect_to charities_path
    else
      flash[:notice] = "Something went wrong"
      redirect_to :back
    end

  end

  def edit
  end

  def update
    if @charity.update(charity_params)
      flash[:noice] = "Charity has been updated"
      redirect_to charities_path
    else
      flash[:notie] = "Something went wrong"
      redirect_to :back
    end
  end

  def destroy
    if @charity.destroy
      flash[:notice] = "Charity has been deleted!"
      redirect_to charities_path
    end
  end

  def vote
    @vote = Vote.create(voteable: @charity, vote: params[:vote], user_id: params[:user_id])

    if @vote.valid?
      flash[:notice] = "Vote was counted!"
      redirect_to charities_path
    else
      flash[:notice] = "you can only vote once"
      redirect_to :back
    end
  end


private
  
  def charity_params
    params.require(:charity).permit(:name, :description, :mission_statement, :avatar, :background_image, :url, :created_at, :updated_at, :vote)
  end

  def set_charity
    @charity = Charity.find_by(id: params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create

    customer = Stripe::Customer.create(
      :source => params[:stripeToken],
      :plan => "gold",
      :email => "#{current_user.email}"
    )

    update_customer_id_and_subscription_id(customer)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
  
  def destroy
    customer = Stripe::Customer.retrieve(current_user.customer_id)
    customer.subscriptions.retrieve(current_user.subscription_id).delete(:at_period_end => true)
  end

private
  def update_customer_id_and_subscription_id(customer)
    stripe_customer_params = JSON.parse(customer.to_s)

    current_user.update_attribute(:customer_id, stripe_customer_params["id"])
    current_user.update_attribute(:subscription_id, stripe_customer_params["subscriptions"]["data"][0]["id"])
    current_user.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/new.html.haml
= form_tag charges_path do
  %article
    - if flash[:error].present?
      #error_explanation
        %p= flash[:error]
    %label.amount
      %span Amount: $1.00
  %script.stripe-button{"data-amount" => "100", "data-description" => "A month's subscription", "data-key" => Rails.configuration.stripe[:publishable_key], "data-locale" => "auto", :src => "https://checkout.stripe.com/checkout.js"}

app/views/charities/edit.html.haml
%h1
  edit

app/views/charities/index.html.haml
.container
  .row
    .col-xs-12
    - if current_user.admin == true
      %a{ href: new_charity_path}
        create charity
      %h1{ style: "text-align: center"}
        All Charities
      - @charities.each do |charity| 
        %a{ href: charity_path(charity), style: "color: #000"}
          .card{ style: "background-image: url(#{charity.avatar})"}
            %h3{ style: "text-align: center"}
              = charity.name
            %h5{ style: "text-align: center"}
              votes: 
              = charity.total_votes

app/views/charities/new.html.haml
.container
  .row
    .col-xs-12
      %h1
        Create Chairty
      = form_for @charity do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: "form-control"
        .form-group
          = f.label :description
          = f.text_area :description, class: "form-control"
        .form-group
          = f.label :mission_statement
          = f.text_area :mission_statement, class: "form-control"
        .form-group
          = f.label :avatar
          = f.text_field :avatar, class: "form-control"
        .form-group
          = f.label :url
          = f.text_field :url, class: "form-control"
        .form-group
          = f.submit "Create", class: "btn btn-primary"

app/views/charities/show.html.haml
.container
  .row
    .col-xs-12
      %h1{ style: "text-align: center" }
        = @charity.name
      %h3{ style: "text-align: center" }
        Total Votes:
        = @charity.total_votes
  .row
    .col-xs-12{style: "height: 200px"}
      %h5{ style: "text-align: center" }
        = @charity.mission_statement
  .row
    .col-xs-12{style: "height: 200px"}
      %h5{ style: "text-align: center" }
        = @charity.description
    - if current_user.customer_id != nil
      %a{ href: vote_charity_path(@charity, vote: true, user_id: current_user.id), data: { method: 'post'} }
        Vote for this Charity!

app/views/layouts/_nav.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-brand
      Vote for Hope
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %h4{ style: "margin-top: 15px"}
            Hello:
            = current_user.username
      %ul.nav.narbar-nav.navbar-right
        %li.pull-right
          %a{ href: logout_path}
            Logout
        - if current_user.customer_id == nil
          %li.pull-right
            %a{ href: new_subscription_path}
              Subscribe
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title VoteForHope
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/nav'
    = yield

app/views/subscriptions/create.html.haml
%h2
  Thanks,
  = current_user.username
  you paid:

  %strong
    $1.00
  

app/views/subscriptions/new.html.haml
= form_tag subscriptions_path do
  %article
    - if flash[:error].present?
      #error_explanation
        %p= flash[:error]
    %label.amount
      %span Amount: $1.00
  %script.stripe-button{"data-amount" => "100", "data-description" => "A month's subscription", "data-key" => Rails.configuration.stripe[:publishable_key], "data-locale" => "auto", :src => "https://checkout.stripe.com/checkout.js"}